language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "QKPgHz31JinkQ9Yl+LAO9yqjhaNkTnJnDRceFiRm5jlpmS0Txj1pKpE6+jniIAzNlbFV9laey7i3MTxiUAG0IXvsgjQaZ8PYEQ7LOzaccI8IhUh0n4Pf4sDfWu6XjwtbOE6Cea3dxLbqO5CdWO7QQrbJoptMug0NquDlBkZL0Ik12CUkntNk9oeiNVXO7m+q/qVIOHbdJKhtz8gw2QshXSrSTrZFaZ/aX8OcimsYgOPpb9jjdD+RCj2LkadRCEEhMvhv7PnrWaQzsk7XMc7C3mzwmvP0gavWcJSqYyXkRi+5n9+G5gyaKKMHg1Z+u5kZpxf/adnbNSr5MrBfNs8FrnLXo+mnIyn6ypjYUstuWeIL4L76prgCxP25E7OObpjfiuvJe0+ERAkOoQlUw2ePAEFAmab5Xvwa6iKenmMv9RCnYeFDnofX60/0V8Ng8wGgHGXoR33JeSpBRspyPoeb9DH4V/NT2AaC2gGsAOCa9q0gTwWFKLRJOuJwjDoVj7VXWxmL7YFaLuXSeQBMtnzY6agwYYSoN+wtIwesV1xf5rJP34XuiFS56bcw1qjBVYcTs5VCsyKOogBbM+AK3+eRdxn6JvxRKH1Sl3v1B6K3gS7Xu42L852JWR5lSZaDnESCaFECkdiGdMQ14N/PvTueXwJq6UJ121i7VybEZDDhdsw="
    - secure: "nZtGpYW+q9yj4qfFwQe5qkUxuzlSLyAhi7Ivz0tzb9qUqFVDgrE5FSknRRKLV5LrunRyeplsypyRYm27IhvQEFm3cWGf8ISVv/BSdgLg9WQw9ZBF5bte/XdtaB8tHQ+CMpNzniNgAUitD0DOXJ+W8friy8mPuJCwWpRKt7RmDaTLsscnR6AZ8zeG2wvDip3B9v199v5fzg0X6G2l3Wpkt0kzzyRaerDH282rMtAB2NMyLJAQUPy/w5ceX4qgFgLK420JEoVUadzH4YKHvippAyt+NUKPb3Z+nM5qIy4swsVBCxKa7YbyLxwKHB9TEvft54IbO5jxXG8v0vyxBiq+3JY8ppY0GKOt77DKKOOPuiTQTW7xjhiDcK84Du0bY+QT5axcbYQ9T4OkYglrg4DX35fzVsIjYWwJOO/knOHGK57HtB9faNrJne37pqaKVqRHwFriIWAuu96s7SnCvIfplddMSDZ8Pb7zPUD5P66285etY1EBusb6827a3Z5V+IKzH2KKMReBlzEwe3UoP74WhQ4h6QDwn3WEQzM1TGmQJHm6h0YLOR1iHJ1g4l6oRtrsO5w8hVPRi1LOCKyUnks5gimhKxaaTlsFCvvKuec1NqVr6YLGaIgPUnNXEx/c3hY7cCdAC9H/UIlBy1cHdhyg4yZ5MfqQgkUxtpfR/XxfF7I="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/